from .models import (
    ArtifactManifestEntry,
    ModelCapabilityProvider,
    ModelAbortSignal,
    ModelClient,
    ModelInvocationMode,
    ModelRequest,
    ModelResponse,
    ModelStreamEvent,
    ModelStreamEventType,
    ModelTerminalMetadata,
    NormalizedModelCapabilities,
    TranscriptArtifact,
    TranscriptEntry,
    TranscriptSession,
    TranscriptStore,
    ToolExecutorTier,
)
from .control_plane import (
    ContextWindowHookFailureMode,
    ContextBudgetHookFailureMode,
    ContextControlPlaneConfig,
    ContextWindowCandidate,
    ContextWindowDecision,
    ContextWindowHook,
    ContextWindowPlan,
    ContextWindowRequest,
    ProviderContextWindowHints,
    ContextPreparationEffect,
    ContextPreparationEffectKind,
    DefaultContextControlPlane,
    DefaultRecoveryPolicy,
    FailureClassification,
    PreparedContext,
    RecoveryDecision,
    RecoveryState,
    StopDisposition,
    StopPhaseOutcome,
)

__all__ = [
    "AttemptFinished",
    "ArtifactManifestEntry",
    "ContextWindowCandidate",
    "ContextWindowDecision",
    "ContextWindowHook",
    "ContextWindowHookFailureMode",
    "ContextWindowPlan",
    "ContextWindowRequest",
    "ContextAssembler",
    "ContextBudgetHookFailureMode",
    "ContextAssembly",
    "ContextControlPlaneConfig",
    "ContextPreparationEffect",
    "ContextPreparationEffectKind",
    "DefaultContextControlPlane",
    "DefaultRecoveryPolicy",
    "FailureClassification",
    "ModelCapabilityProvider",
    "ModelAbortSignal",
    "ModelClient",
    "ModelInvocationMode",
    "ModelRequest",
    "ModelResponse",
    "ModelStreamEvent",
    "ModelStreamEventType",
    "ModelTerminalMetadata",
    "NormalizedModelCapabilities",
    "PromptComposer",
    "PromptComposition",
    "PreparedContext",
    "ProviderContextWindowHints",
    "RecoveryDecision",
    "RecoveryState",
    "StopDisposition",
    "StopPhaseOutcome",
    "TranscriptArtifact",
    "TranscriptEntry",
    "TranscriptSession",
    "TranscriptStore",
    "ToolExecutorTier",
    "TurnStreamEvent",
    "TurnStreamEventType",
    "TurnLoopState",
    "TurnPhase",
    "TurnPostEffects",
    "TurnRecoveryAction",
    "TurnTerminal",
    "TurnTerminalReason",
    "TurnTransition",
    "TurnTransitionReason",
    "TurnEngine",
    "TurnResult",
]


def __getattr__(name: str):
    if name in {"ContextAssembler", "ContextAssembly", "PromptComposer", "PromptComposition"}:
        from .composer import ContextAssembler, ContextAssembly, PromptComposer, PromptComposition

        return {
            "ContextAssembler": ContextAssembler,
            "ContextAssembly": ContextAssembly,
            "PromptComposer": PromptComposer,
            "PromptComposition": PromptComposition,
        }[name]
    if name in {
        "AttemptFinished",
        "TurnEngine",
        "TurnLoopState",
        "TurnPhase",
        "TurnPostEffects",
        "TurnRecoveryAction",
        "TurnResult",
        "TurnStreamEvent",
        "TurnStreamEventType",
        "TurnTerminal",
        "TurnTerminalReason",
        "TurnTransition",
        "TurnTransitionReason",
    }:
        from .engine import (
            AttemptFinished,
            TurnEngine,
            TurnLoopState,
            TurnPhase,
            TurnPostEffects,
            TurnRecoveryAction,
            TurnResult,
            TurnStreamEvent,
            TurnStreamEventType,
            TurnTerminal,
            TurnTerminalReason,
            TurnTransition,
            TurnTransitionReason,
        )

        return {
            "AttemptFinished": AttemptFinished,
            "TurnEngine": TurnEngine,
            "TurnLoopState": TurnLoopState,
            "TurnPhase": TurnPhase,
            "TurnPostEffects": TurnPostEffects,
            "TurnRecoveryAction": TurnRecoveryAction,
            "TurnResult": TurnResult,
            "TurnStreamEvent": TurnStreamEvent,
            "TurnStreamEventType": TurnStreamEventType,
            "TurnTerminal": TurnTerminal,
            "TurnTerminalReason": TurnTerminalReason,
            "TurnTransition": TurnTransition,
            "TurnTransitionReason": TurnTransitionReason,
        }[name]
    raise AttributeError(name)
