from __future__ import annotations

from ..definitions import (
    DefinitionOrigin,
    DefinitionSource,
    InterruptBehavior,
    ToolCallStatus,
    ToolClassifierInput,
    ToolDefinition,
    ToolFailureClassifier,
    ToolFailureMode,
    ToolFailurePolicy,
    ToolPresentationEmphasis,
    ToolRiskLevel,
    ToolTraits,
    ToolUsePresentation,
)
from .definition_helpers import static_semantics
from .tool_impls import (
    agent_tool,
    ask_permission,
    ask_user_tool,
    job_get_tool,
    job_list_tool,
    job_stop_tool,
    skill_tool,
    sleep_tool,
    task_archive_tool,
    task_assign_next_tool,
    task_block_tool,
    task_claim_tool,
    task_create_tool,
    task_delete_tool,
    task_get_tool,
    task_list_tool,
    task_release_tool,
    task_unblock_tool,
    task_unarchive_tool,
    task_update_tool,
    validate_agent_tool,
    validate_skill_registry_entry,
    validate_sleep_tool,
)


def builtin_tools() -> tuple[ToolDefinition, ...]:
    origin = DefinitionOrigin(DefinitionSource.BUNDLED)
    return (
        ToolDefinition(
            name="agent",
            aliases=("Agent",),
            description="Spawn or communicate with a subagent.",
            input_schema={
                "type": "object",
                "properties": {
                    "agent": {"type": "string"},
                    "prompt": {"type": "string"},
                    "background": {"type": "boolean"},
                    "spawn_mode": {
                        "type": "string",
                        "enum": ["sync", "background"],
                    },
                    "cwd": {"type": "string"},
                    "model": {"type": "string"},
                    "model_route": {"type": "string"},
                    "reason": {"type": "string"},
                    "permission_mode": {
                        "type": "string",
                        "enum": [
                            "default",
                            "plan",
                            "acceptEdits",
                            "bypassPermissions",
                            "dontAsk",
                            "auto",
                            "bubble",
                        ],
                    },
                    "isolation": {
                        "type": "string",
                        "enum": ["none", "worktree", "remote"],
                    },
                    "max_turns": {"type": "integer", "minimum": 1},
                },
                "required": ["agent", "prompt"],
                "additionalProperties": False,
            },
            output_schema={
                "type": "object",
                "properties": {
                    "agent": {"type": "string"},
                    "status": {"type": "string"},
                    "background": {"type": "boolean"},
                    "run_id": {"type": ["string", "null"]},
                    "parent_run_id": {"type": ["string", "null"]},
                    "turn_id": {"type": ["string", "null"]},
                    "query_source": {"type": ["string", "null"]},
                    "parent_turn_id": {"type": ["string", "null"]},
                    "spawn_mode": {"type": ["string", "null"]},
                    "delegation_depth": {"type": "integer"},
                    "summary": {"type": "string"},
                    "scope_summary": {
                        "type": ["object", "null"],
                        "properties": {
                            "visible_tools": {
                                "type": "array",
                                "items": {"type": "string"},
                            },
                            "visible_skills": {
                                "type": "array",
                                "items": {"type": "string"},
                            },
                            "permission_mode": {"type": ["string", "null"]},
                            "isolation_mode": {"type": ["string", "null"]},
                            "memory_scope": {"type": ["string", "null"]},
                        },
                        "required": [
                            "visible_tools",
                            "visible_skills",
                            "permission_mode",
                            "isolation_mode",
                            "memory_scope",
                        ],
                        "additionalProperties": True,
                    },
                    "messages": {"type": "array"},
                    "task_id": {"type": ["string", "null"]},
                    "requested_model": {"type": ["string", "null"]},
                    "requested_model_route": {"type": ["string", "null"]},
                    "resolved_model_route": {"type": ["string", "null"]},
                    "isolation_mode": {"type": ["string", "null"]},
                    "terminal_metadata": {"type": "object"},
                    "notification": {"type": ["object", "null"]},
                },
                "required": [
                    "agent",
                    "status",
                    "background",
                    "run_id",
                    "parent_run_id",
                    "turn_id",
                    "query_source",
                    "summary",
                    "requested_model",
                    "requested_model_route",
                    "resolved_model_route",
                    "terminal_metadata",
                ],
                "additionalProperties": True,
            },
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                tool_use_presentation=lambda tool_input, _context: ToolUsePresentation(
                    title="Run agent",
                    subtitle=tool_input.get("agent"),
                    emphasis=ToolPresentationEmphasis.NORMAL,
                ),
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="agent",
                    summary=f"Delegate to agent: {tool_input['agent']}",
                    risk_level=ToolRiskLevel.DELEGATE,
                    side_effects=True,
                    tags=("delegate", "agent"),
                ),
            ),
            validate_input=validate_agent_tool,
            execute=agent_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="skill",
            aliases=("Skill",),
            description="Invoke a registered runtime skill.",
            input_schema={
                "type": "object",
                "properties": {
                    "skill": {"type": "string"},
                    "arguments": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                },
                "required": ["skill"],
                "additionalProperties": False,
            },
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                tool_use_presentation=lambda tool_input, _context: ToolUsePresentation(
                    title="Run skill",
                    subtitle=tool_input.get("skill"),
                    emphasis=ToolPresentationEmphasis.NORMAL,
                ),
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="skill",
                    summary=f"Run skill: {tool_input['skill']}",
                    risk_level=ToolRiskLevel.DELEGATE,
                    side_effects=True,
                    tags=("delegate", "skill"),
                ),
            ),
            validate_input=validate_skill_registry_entry,
            execute=skill_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="task_create",
            description="Create a planning task in the resolved shared task list.",
            input_schema={
                "type": "object",
                "properties": {
                    "subject": {"type": "string"},
                    "description": {"type": "string"},
                    "active_form": {"type": "string"},
                    "owner": {"type": "string"},
                    "blocks": {"type": "array", "items": {"type": "string"}},
                    "blocked_by": {"type": "array", "items": {"type": "string"}},
                    "metadata": {"type": "object"},
                },
                "required": ["subject"],
                "additionalProperties": False,
            },
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="task_create",
                    summary=f"Create task: {tool_input['subject']}",
                    risk_level=ToolRiskLevel.WRITE,
                    side_effects=True,
                    tags=("task", "write"),
                ),
            ),
            execute=task_create_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="task_get",
            description="Inspect a planning task in the resolved shared task list.",
            input_schema={
                "type": "object",
                "properties": {"task_id": {"type": "string"}},
                "required": ["task_id"],
                "additionalProperties": False,
            },
            traits=ToolTraits(read_only=True, concurrency_safe=True),
            semantics=static_semantics(
                read_only=True,
                concurrency_safe=True,
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="task_get",
                    summary=f"Inspect task: {tool_input['task_id']}",
                    risk_level=ToolRiskLevel.READ,
                    side_effects=False,
                    tags=("task", "read"),
                ),
            ),
            execute=task_get_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="task_update",
            description="Update non-orchestration fields on a planning task in the resolved shared task list.",
            input_schema={
                "type": "object",
                "properties": {
                    "task_id": {"type": "string"},
                    "status": {
                        "type": "string",
                        "enum": ["pending", "in_progress", "completed"],
                    },
                    "subject": {"type": "string"},
                    "description": {"type": "string"},
                    "active_form": {"type": "string"},
                    "metadata": {"type": "object"},
                },
                "required": ["task_id"],
                "additionalProperties": False,
            },
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="task_update",
                    summary=f"Update task: {tool_input['task_id']}",
                    risk_level=ToolRiskLevel.WRITE,
                    side_effects=True,
                    tags=("task", "write"),
                ),
            ),
            execute=task_update_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="task_archive",
            description="Archive a completed planning task without deleting its record.",
            input_schema={
                "type": "object",
                "properties": {"task_id": {"type": "string"}},
                "required": ["task_id"],
                "additionalProperties": False,
            },
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="task_archive",
                    summary=f"Archive task: {tool_input['task_id']}",
                    risk_level=ToolRiskLevel.WRITE,
                    side_effects=True,
                    tags=("task", "write", "retirement"),
                ),
            ),
            execute=task_archive_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="task_unarchive",
            description="Restore an archived planning task to the active completed state.",
            input_schema={
                "type": "object",
                "properties": {"task_id": {"type": "string"}},
                "required": ["task_id"],
                "additionalProperties": False,
            },
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="task_unarchive",
                    summary=f"Unarchive task: {tool_input['task_id']}",
                    risk_level=ToolRiskLevel.WRITE,
                    side_effects=True,
                    tags=("task", "write", "retirement"),
                ),
            ),
            execute=task_unarchive_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="task_delete",
            description="Delete an archived planning task and clean dangling dependency edges.",
            input_schema={
                "type": "object",
                "properties": {"task_id": {"type": "string"}},
                "required": ["task_id"],
                "additionalProperties": False,
            },
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="task_delete",
                    summary=f"Delete task: {tool_input['task_id']}",
                    risk_level=ToolRiskLevel.WRITE,
                    side_effects=True,
                    tags=("task", "write", "retirement"),
                ),
            ),
            execute=task_delete_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="task_claim",
            description="Atomically claim a planning task through the runtime orchestration control plane.",
            input_schema={
                "type": "object",
                "properties": {
                    "task_id": {"type": "string"},
                    "owner": {"type": "string"},
                    "set_in_progress": {"type": "boolean"},
                    "enforce_owner_busy": {"type": "boolean"},
                },
                "required": ["task_id"],
                "additionalProperties": False,
            },
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="task_claim",
                    summary=f"Claim task: {tool_input['task_id']}",
                    risk_level=ToolRiskLevel.WRITE,
                    side_effects=True,
                    tags=("task", "write", "orchestration"),
                ),
            ),
            execute=task_claim_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="task_release",
            description="Release a planning task claim through the runtime orchestration control plane.",
            input_schema={
                "type": "object",
                "properties": {
                    "task_id": {"type": "string"},
                },
                "required": ["task_id"],
                "additionalProperties": False,
            },
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="task_release",
                    summary=f"Release task: {tool_input['task_id']}",
                    risk_level=ToolRiskLevel.WRITE,
                    side_effects=True,
                    tags=("task", "write", "orchestration"),
                ),
            ),
            execute=task_release_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="task_assign_next",
            description="Atomically claim the next available planning task from the resolved shared task list.",
            input_schema={
                "type": "object",
                "properties": {
                    "owner": {"type": "string"},
                    "set_in_progress": {"type": "boolean"},
                    "enforce_owner_busy": {"type": "boolean"},
                },
                "additionalProperties": False,
            },
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                classifier_input=lambda _tool_input, _context: ToolClassifierInput(
                    operation="task_assign_next",
                    summary="Assign next available task",
                    risk_level=ToolRiskLevel.WRITE,
                    side_effects=True,
                    tags=("task", "write", "orchestration"),
                ),
            ),
            execute=task_assign_next_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="task_block",
            description="Add a validated dependency edge where one planning task blocks another.",
            input_schema={
                "type": "object",
                "properties": {
                    "blocker_task_id": {"type": "string"},
                    "blocked_task_id": {"type": "string"},
                },
                "required": ["blocker_task_id", "blocked_task_id"],
                "additionalProperties": False,
            },
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="task_block",
                    summary=(
                        f"Add dependency: {tool_input['blocker_task_id']} -> "
                        f"{tool_input['blocked_task_id']}"
                    ),
                    risk_level=ToolRiskLevel.WRITE,
                    side_effects=True,
                    tags=("task", "write", "orchestration"),
                ),
            ),
            execute=task_block_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="task_unblock",
            description="Remove a validated dependency edge between planning tasks.",
            input_schema={
                "type": "object",
                "properties": {
                    "blocker_task_id": {"type": "string"},
                    "blocked_task_id": {"type": "string"},
                },
                "required": ["blocker_task_id", "blocked_task_id"],
                "additionalProperties": False,
            },
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="task_unblock",
                    summary=(
                        f"Remove dependency: {tool_input['blocker_task_id']} -> "
                        f"{tool_input['blocked_task_id']}"
                    ),
                    risk_level=ToolRiskLevel.WRITE,
                    side_effects=True,
                    tags=("task", "write", "orchestration"),
                ),
            ),
            execute=task_unblock_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="task_list",
            description="List planning tasks and derived readiness state from the resolved shared task list.",
            input_schema={
                "type": "object",
                "properties": {
                    "include_archived": {"type": "boolean"},
                },
                "additionalProperties": False,
            },
            traits=ToolTraits(read_only=True, concurrency_safe=True),
            semantics=static_semantics(
                read_only=True,
                concurrency_safe=True,
                classifier_input=lambda _tool_input, _context: ToolClassifierInput(
                    operation="task_list",
                    summary="List tasks",
                    risk_level=ToolRiskLevel.READ,
                    side_effects=False,
                    tags=("task", "read"),
                ),
            ),
            execute=task_list_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="job_get",
            description="Inspect a background job visible to the current execution scope.",
            input_schema={
                "type": "object",
                "properties": {"job_id": {"type": "string"}},
                "required": ["job_id"],
                "additionalProperties": False,
            },
            traits=ToolTraits(read_only=True, concurrency_safe=True),
            semantics=static_semantics(
                read_only=True,
                concurrency_safe=True,
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="job_get",
                    summary=f"Inspect job: {tool_input['job_id']}",
                    risk_level=ToolRiskLevel.READ,
                    side_effects=False,
                    tags=("job", "read"),
                ),
            ),
            execute=job_get_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="job_list",
            description="List background jobs visible to the current execution scope.",
            input_schema={
                "type": "object",
                "properties": {},
                "additionalProperties": False,
            },
            traits=ToolTraits(read_only=True, concurrency_safe=True),
            semantics=static_semantics(
                read_only=True,
                concurrency_safe=True,
                classifier_input=lambda _tool_input, _context: ToolClassifierInput(
                    operation="job_list",
                    summary="List jobs",
                    risk_level=ToolRiskLevel.READ,
                    side_effects=False,
                    tags=("job", "read"),
                ),
            ),
            execute=job_list_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="job_stop",
            description="Stop a running background job visible to the current execution scope.",
            input_schema={
                "type": "object",
                "properties": {"job_id": {"type": "string"}},
                "required": ["job_id"],
                "additionalProperties": False,
            },
            traits=ToolTraits(destructive=True),
            semantics=static_semantics(
                read_only=False,
                concurrency_safe=False,
                failure_policy=ToolFailurePolicy(
                    failure_mode=ToolFailureMode.ERROR_RESULT,
                    result_classifier=ToolFailureClassifier.EXCEPTION_ONLY,
                    surfaced_status=ToolCallStatus.ERROR,
                ),
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="job_stop",
                    summary=f"Stop job: {tool_input['job_id']}",
                    risk_level=ToolRiskLevel.WRITE,
                    side_effects=True,
                    tags=("job", "write"),
                ),
            ),
            check_permissions=ask_permission,
            execute=job_stop_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="ask_user",
            aliases=("AskUser",),
            description="Request explicit user input from the host.",
            input_schema={
                "type": "object",
                "properties": {
                    "question": {"type": "string"},
                    "options": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                },
                "required": ["question"],
                "additionalProperties": False,
            },
            execute=ask_user_tool,
            runtime_execution_class="privileged",
            origin=origin,
        ),
        ToolDefinition(
            name="sleep",
            aliases=("Sleep",),
            description="Pause for a bounded duration without blocking forever.",
            input_schema={
                "type": "object",
                "properties": {"seconds": {"type": "number", "minimum": 0, "maximum": 300}},
                "required": ["seconds"],
                "additionalProperties": False,
            },
            traits=ToolTraits(interrupt_behavior=InterruptBehavior.CANCEL),
            semantics=static_semantics(
                read_only=True,
                concurrency_safe=True,
                interrupt_behavior=InterruptBehavior.CANCEL,
                classifier_input=lambda tool_input, _context: ToolClassifierInput(
                    operation="sleep",
                    summary=f"Sleep for {tool_input['seconds']} seconds",
                    risk_level=ToolRiskLevel.READ,
                    side_effects=False,
                    tags=("timing",),
                ),
            ),
            validate_input=validate_sleep_tool,
            execute=sleep_tool,
            origin=origin,
        ),
    )
