from __future__ import annotations

from ..definitions import (
    DefinitionOrigin,
    DefinitionSource,
    InterruptBehavior,
    ToolDefinition,
    ToolTraits,
)
from .tool_impls import (
    agent_tool,
    ask_permission,
    ask_user_tool,
    bash_tool,
    edit_file_tool,
    glob_tool,
    grep_tool,
    read_file_tool,
    skill_tool,
    sleep_tool,
    task_create_tool,
    task_get_tool,
    task_list_tool,
    task_stop_tool,
    task_update_tool,
    validate_agent_registry_entry,
    validate_bash_tool,
    validate_edit_tool,
    validate_read_tool,
    validate_skill_registry_entry,
    validate_sleep_tool,
    validate_url_tool,
    validate_web_search,
    validate_write_tool,
    web_fetch_tool,
    web_search_tool,
    write_file_tool,
)


def builtin_tools() -> tuple[ToolDefinition, ...]:
    origin = DefinitionOrigin(DefinitionSource.BUNDLED)
    return (
        ToolDefinition(
            name="read",
            aliases=("Read",),
            description="Read files from the workspace without modifying them.",
            search_hint="read files",
            input_schema={
                "type": "object",
                "properties": {
                    "file_path": {"type": "string"},
                    "offset": {"type": "integer", "minimum": 0},
                    "limit": {"type": "integer", "minimum": 1},
                },
                "required": ["file_path"],
                "additionalProperties": False,
            },
            traits=ToolTraits(read_only=True, concurrency_safe=True),
            validate_input=validate_read_tool,
            execute=read_file_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="glob",
            aliases=("Glob",),
            description="Match filesystem paths using glob patterns.",
            search_hint="search file paths",
            input_schema={
                "type": "object",
                "properties": {
                    "pattern": {"type": "string"},
                    "root": {"type": "string"},
                },
                "required": ["pattern"],
                "additionalProperties": False,
            },
            traits=ToolTraits(read_only=True, concurrency_safe=True),
            execute=glob_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="grep",
            aliases=("Grep",),
            description="Search file contents using regular expressions.",
            search_hint="search file contents",
            input_schema={
                "type": "object",
                "properties": {
                    "pattern": {"type": "string"},
                    "path": {"type": "string"},
                    "case_sensitive": {"type": "boolean"},
                },
                "required": ["pattern"],
                "additionalProperties": False,
            },
            traits=ToolTraits(read_only=True, concurrency_safe=True),
            execute=grep_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="edit",
            aliases=("Edit",),
            description="Apply targeted edits to an existing file.",
            input_schema={
                "type": "object",
                "properties": {
                    "file_path": {"type": "string"},
                    "old_string": {"type": "string"},
                    "new_string": {"type": "string"},
                    "replace_all": {"type": "boolean"},
                },
                "required": ["file_path", "old_string", "new_string"],
                "additionalProperties": False,
            },
            validate_input=validate_edit_tool,
            check_permissions=ask_permission,
            execute=edit_file_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="write",
            aliases=("Write",),
            description="Write a full file payload to disk.",
            input_schema={
                "type": "object",
                "properties": {
                    "file_path": {"type": "string"},
                    "content": {"type": "string"},
                },
                "required": ["file_path", "content"],
                "additionalProperties": False,
            },
            traits=ToolTraits(destructive=True),
            validate_input=validate_write_tool,
            check_permissions=ask_permission,
            execute=write_file_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="bash",
            aliases=("Bash",),
            description="Run a shell command in the current environment.",
            input_schema={
                "type": "object",
                "properties": {
                    "command": {"type": "string"},
                    "cwd": {"type": "string"},
                    "timeout_ms": {"type": "integer", "minimum": 1},
                },
                "required": ["command"],
                "additionalProperties": False,
            },
            validate_input=validate_bash_tool,
            check_permissions=ask_permission,
            execute=bash_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="web_fetch",
            aliases=("WebFetch",),
            description="Fetch a single remote resource and return its content.",
            input_schema={
                "type": "object",
                "properties": {
                    "url": {"type": "string"},
                    "timeout_ms": {"type": "integer", "minimum": 1},
                },
                "required": ["url"],
                "additionalProperties": False,
            },
            traits=ToolTraits(read_only=True, concurrency_safe=True),
            validate_input=validate_url_tool,
            execute=web_fetch_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="web_search",
            aliases=("WebSearch",),
            description="Search the web for recent information.",
            input_schema={
                "type": "object",
                "properties": {
                    "query": {"type": "string"},
                    "limit": {"type": "integer", "minimum": 1, "maximum": 10},
                },
                "required": ["query"],
                "additionalProperties": False,
            },
            traits=ToolTraits(read_only=True, concurrency_safe=True),
            validate_input=validate_web_search,
            execute=web_search_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="agent",
            aliases=("Agent",),
            description="Spawn or communicate with a subagent.",
            input_schema={
                "type": "object",
                "properties": {
                    "agent": {"type": "string"},
                    "prompt": {"type": "string"},
                    "background": {"type": "boolean"},
                },
                "required": ["agent", "prompt"],
                "additionalProperties": False,
            },
            validate_input=validate_agent_registry_entry,
            execute=agent_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="skill",
            aliases=("Skill",),
            description="Invoke a registered runtime skill.",
            input_schema={
                "type": "object",
                "properties": {
                    "skill": {"type": "string"},
                    "arguments": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                },
                "required": ["skill"],
                "additionalProperties": False,
            },
            validate_input=validate_skill_registry_entry,
            execute=skill_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="task_create",
            description="Create a background task record.",
            input_schema={
                "type": "object",
                "properties": {
                    "task_id": {"type": "string"},
                    "title": {"type": "string"},
                    "description": {"type": "string"},
                    "metadata": {"type": "object"},
                },
                "required": ["task_id", "title"],
                "additionalProperties": False,
            },
            execute=task_create_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="task_get",
            description="Inspect a task by identifier.",
            input_schema={
                "type": "object",
                "properties": {"task_id": {"type": "string"}},
                "required": ["task_id"],
                "additionalProperties": False,
            },
            traits=ToolTraits(read_only=True, concurrency_safe=True),
            execute=task_get_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="task_update",
            description="Update a task state or metadata.",
            input_schema={
                "type": "object",
                "properties": {
                    "task_id": {"type": "string"},
                    "status": {
                        "type": "string",
                        "enum": ["pending", "running", "completed", "failed", "stopped"],
                    },
                    "result": {},
                    "error": {"type": "string"},
                    "metadata": {"type": "object"},
                },
                "required": ["task_id"],
                "additionalProperties": False,
            },
            execute=task_update_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="task_list",
            description="List tracked tasks for the current session.",
            input_schema={
                "type": "object",
                "properties": {},
                "additionalProperties": False,
            },
            traits=ToolTraits(read_only=True, concurrency_safe=True),
            execute=task_list_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="task_stop",
            aliases=("TaskStop",),
            description="Stop a running task or background process.",
            input_schema={
                "type": "object",
                "properties": {"task_id": {"type": "string"}},
                "required": ["task_id"],
                "additionalProperties": False,
            },
            traits=ToolTraits(destructive=True),
            check_permissions=ask_permission,
            execute=task_stop_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="ask_user",
            aliases=("AskUser",),
            description="Request explicit user input from the host.",
            input_schema={
                "type": "object",
                "properties": {
                    "question": {"type": "string"},
                    "options": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                },
                "required": ["question"],
                "additionalProperties": False,
            },
            execute=ask_user_tool,
            origin=origin,
        ),
        ToolDefinition(
            name="sleep",
            aliases=("Sleep",),
            description="Pause for a bounded duration without blocking forever.",
            input_schema={
                "type": "object",
                "properties": {"seconds": {"type": "number", "minimum": 0, "maximum": 300}},
                "required": ["seconds"],
                "additionalProperties": False,
            },
            traits=ToolTraits(interrupt_behavior=InterruptBehavior.CANCEL),
            validate_input=validate_sleep_tool,
            execute=sleep_tool,
            origin=origin,
        ),
    )
